language: cpp
compiler:
  - gcc
  - clang
script: ./autogen.sh && ./configure && make
before_script:
  - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu saucy main universe restricted multiverse"
  - sudo apt-get update -qq
  - sudo apt-get -qq install libboost-all-dev libsdl2-dev libopenal-dev libfreetype6-dev libmad0-dev libfaad-dev libvorbis-dev libxvidcore-dev libgl1-mesa-dev zlib1g-dev liblzma-dev

notifications:
  email:
    recipients:
      - ndbrandes@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#xoreos"
    on_success: change
    on_failure: always
    use_notice: true
