language: cpp
compiler:
  - gcc
  - clang
script: ./autogen.sh && ./configure && make
before_script:
  - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu saucy main universe restricted multiverse"
  - sudo apt-get update -qq
  - sudo apt-get -qq install libboost-all-dev libsdl2-dev libopenal-dev libfreetype6-dev libmad0-dev libfaad-dev libvorbis-dev libxvidcore-dev libgl1-mesa-dev zlib1g-dev liblzma-dev

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "oYIV1EmOvP2ruIxyCTPuGuqUsUzTxxu3P+IdlQZgV6aXaBxtFCuoQaLVMOlnx8xSI2V4mb5I/wK5fAtgUAomzDHQmaBNSbJc3xBTy2xgckup60ehKtFqf+ifm+AYcLQQgLtMUDmLNNcJIKUGPZ8GYwjNfWKt3VGuLHV+UFiRuQI="

addons:
  coverity_scan:
    project:
      name: "xoreos/xoreos"
      description: "Build submitted via Travis CI"
    notification_email: drmccoy@drmccoy.de
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - ndbrandes@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#xoreos"
    on_success: change
    on_failure: always
    use_notice: true
